# Pin python:3.12-slim by digest for reproducible builds. Bump in BOTH FROM lines together.
# Refresh procedure (also in CONTRIBUTING.md → Bumping the NATS Image Digest):
#   docker pull python:3.12-slim
#   docker inspect --format '{{index .RepoDigests 0}}' python:3.12-slim
FROM python:3.12-slim@sha256:ec948fa5f90f4f8907e89f4800cfd2d2e91e391a4bce4a6afa77ba265bc3a2fe AS builder
WORKDIR /build
COPY requirements.lock.txt .
# requirements.lock.txt is generated by `just lock` (pip-compile --generate-hashes)
# against Python 3.12 to match the runtime stage's interpreter. --require-hashes
# forces every requirement to be pinned by digest in the file; pip refuses to
# resolve anything else, guaranteeing reproducible builds. See issue #354.
RUN pip install --no-cache-dir --require-hashes \
        --target /build/deps -r requirements.lock.txt

FROM python:3.12-slim@sha256:ec948fa5f90f4f8907e89f4800cfd2d2e91e391a4bce4a6afa77ba265bc3a2fe
WORKDIR /app

# Install tini for PID-1 signal forwarding. The python:3.12-slim base image is already
# pinned by SHA256 digest above, which makes the tini package version reproducible
# without an apt version pin (apt pins drift as Debian rebuilds packages even when
# upstream version is unchanged, e.g. 0.19.0-1 → 0.19.0-1build1).
RUN apt-get update \
    && apt-get install -y --no-install-recommends tini \
    && rm -rf /var/lib/apt/lists/*

# Install curl for the HEALTHCHECK directive below. Intentionally NOT version-pinned
# to avoid bumping in lockstep with the base image; the HEALTHCHECK only uses curl's
# stable -f flag. See issue #561.
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/deps /usr/local/lib/python3.12/site-packages/
COPY src/hermes/ ./hermes/

RUN useradd -r -s /usr/sbin/nologin hermes
USER hermes

ENV HERMES_HOST=0.0.0.0
ENV HERMES_PORT=8085
ENV HERMES_PUBLIC_URL=http://localhost:8085
ENV PYTHONDONTWRITEBYTECODE=1
EXPOSE 8085

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -f http://localhost:${HERMES_PORT:-8085}/ready || exit 1

ENTRYPOINT ["tini", "--"]
CMD ["python", "-m", "hermes.server"]
