#!/usr/bin/env python3
"""Generate or validate requirements.txt from pixi.lock via `pixi list --json`.

Usage:
    python scripts/sync_requirements.py           # (re)generate requirements.txt
    python scripts/sync_requirements.py --check   # exit 1 if out of sync
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # py<3.11
    import tomli as tomllib  # type: ignore[import-not-found,no-redef,unused-ignore]

REPO_ROOT = Path(__file__).parent.parent
REQUIREMENTS_FILE = REPO_ROOT / "requirements.txt"
PYPROJECT = REPO_ROOT / "pyproject.toml"
HEADER = (
    "# Auto-generated by scripts/sync_requirements.py — do not edit by hand.\n"
    "# Source: pixi list --json (reads pixi.lock); names from pyproject.toml.\n"
    "# Regenerate: just sync-reqs\n"
)
_NAME_RE = re.compile(r"^\s*([A-Za-z0-9_.\-]+)(?:\[([^\]]*)\])?")


def _canon(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _runtime_deps() -> dict[str, str]:
    """{canonical-name: extras-suffix} from pyproject [project.dependencies]."""
    data = tomllib.loads(PYPROJECT.read_text())
    out: dict[str, str] = {}
    for entry in data["project"]["dependencies"]:
        m = _NAME_RE.match(entry.split(";", 1)[0])
        if not m:
            sys.exit(f"ERROR: cannot parse dependency {entry!r} in pyproject.toml")
        extras = f"[{m.group(2)}]" if m.group(2) else ""
        out[_canon(m.group(1))] = extras
    return out


def _pixi_versions() -> dict[str, str]:
    result = subprocess.run(
        ["pixi", "list", "--json"],
        capture_output=True,
        text=True,
        check=True,
        cwd=REPO_ROOT,
    )
    return {
        _canon(p["name"]): p["version"]
        for p in json.loads(result.stdout)
        if p.get("kind") == "pypi"
    }


def _build_lines() -> list[str]:
    deps = _runtime_deps()
    versions = _pixi_versions()
    missing = sorted(deps.keys() - versions.keys())
    if missing:
        sys.exit(f"ERROR: runtime deps not found in `pixi list` output: {missing}")
    return [f"{name}{deps[name]}=={versions[name]}" for name in sorted(deps)]


def generate() -> None:
    content = HEADER + "\n".join(_build_lines()) + "\n"
    REQUIREMENTS_FILE.write_text(content)
    try:
        display = REQUIREMENTS_FILE.relative_to(REPO_ROOT)
    except ValueError:
        display = REQUIREMENTS_FILE
    print(f"Wrote {display} ({content.count('==')} packages)")


def check() -> None:
    if not REQUIREMENTS_FILE.exists():
        sys.exit(f"ERROR: {REQUIREMENTS_FILE} does not exist. Run: just sync-reqs")
    expected = HEADER + "\n".join(_build_lines()) + "\n"
    if REQUIREMENTS_FILE.read_text() == expected:
        print("OK: requirements.txt is in sync with pixi.lock")
        return
    sys.exit(
        "ERROR: requirements.txt is out of sync with pixi.lock.\n"
        "       Regenerate with: just sync-reqs"
    )


def main() -> None:
    check() if "--check" in sys.argv else generate()


if __name__ == "__main__":
    main()
